# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  initialize:
    description: Install Prerequisites for build
      executor: 
        name: windows/default
      steps:
        - checkout
        - restore_cache:
            keys:
              - dotnet-packages-v1-{{ checksum "XXXXXXX"}}
        - run:
            name: "Install Project Dependecies"
            command: dotnet.exe restore
        - save_cache:
            paths:
              - C:\User\circleci\.nuget\packages
            key: dotnet-packages-v1-{{ checksum "XXXXXXX"}}
  build:
    description: Build application with release configs
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: Build web api for release
          command: dotnet.exe build --configuration release
workflows:
  initialize_and_build:
    jobs:
      - initialize
      - build:
          requires:
            - initialize
