# Couldn't automatically generate a config from your source code.
# This is a generic template to serve as a base for your custom config
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  windows: circleci/windows@5.0

jobs:
  build-and-test:
    executor:
      name: win/default
      version: edge
    steps:
      - checkout
      - run:
          name: "Install Project Dependecies"
          command: dotnet.exe restore
      - run:
          name: "Build web api for release"
          command: dotnet.exe build --configuration release
workflows:
  build-and-unittest:
    jobs:
      - build-and-test
  
   
    

      
            
